FROM openshift3/ose:latest

# Jenkins image for OpenShift
#
# This image provides a Jenkins server, primarily intended for integration with
# OpenShift v3.
#
# Volumes: 
# * /var/jenkins_home
# Environment:
# * $JENKINS_PASSWORD - Password for the Jenkins 'admin' user.

MAINTAINER Ben Parees <bparees@redhat.com>, Aleksandar Lazic <aleksandar.lazic@cloudwerkstatt.com

# latest lts
# http://mirrors.jenkins-ci.org/war-stable/latest/jenkins.war
# the version dir is
# http://mirrors.jenkins-ci.org/war-stable/2.7.4/jenkins.war

ENV JENKINS_VERSION=2.7.4 \
    HOME=/var/lib/jenkins \
    JENKINS_HOME=/var/lib/jenkins \
    STI_SCRIPTS_URL=image:///usr/libexec/s2i \
    KUBERNETES_URL=http://updates.jenkins-ci.org/download/plugins/kubernetes/0.8/kubernetes.hpi \
    DUR_TASK_URL=http://updates.jenkins-ci.org/download/plugins/durable-task/1.12/durable-task.hpi \
    

LABEL k8s.io.description="Jenkins is a continuous integration server" \
      k8s.io.display-name="Jenkins 2.7.4" \
      openshift.io.expose-services="8080:http" \
      openshift.io.tags="jenkins,jenkins2,ci" \
      io.openshift.s2i.scripts-url=image:///usr/libexec/s2i

# Labels consumed by Red Hat build service
#LABEL BZComponent="openshift-jenkins-docker" \
#      Name="openshift3/jenkins-1-rhel7" \
LABEL Version="2.7.4" \
      Architecture="x86_64" \
      Release="8"

# 8080 for main web interface, 50000 for slave agents
EXPOSE 8080 50000

#orig packages
# INSTALL_PKGS="rsync gettext git tar zip unzip nss_wrapper java-1.8.0-openjdk atomic-openshift-clients jenkins jenkins-plugin-kubernetes jenkins-plugin-openshift-pipeline jenkins-plugin-credentials" && \
RUN yum-config-manager --enable rhel-7-server-ose-3.2-rpms && \
    INSTALL_PKGS="rsync gettext git tar zip unzip nss_wrapper java-1.8.0-openjdk atomic-openshift-clients" && \
    yum install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all  && \
    localedef -f UTF-8 -i en_US en_US.UTF-8

# COPY ./contrib/openshift /opt/openshift
# COPY ./contrib/jenkins /usr/local/bin
# ADD ./contrib/s2i /usr/libexec/s2i

# NOTE: When adding new Jenkins plugin, you have to create the symlink for the
# HPI file created by rpm to /opt/openshift/plugins folder.
RUN mkdir -p /opt/openshift/plugins && \
    ln -s /usr/lib64/jenkins/openshift-pipeline.hpi /opt/openshift/plugins/openshift-pipeline.hpi && \
    ln -s /usr/lib64/jenkins/credentials.hpi /opt/openshift/plugins/credentials.hpi && \
    # Prefer the latest version of the credentials plugin over the bundled
    # version.
    touch /opt/openshift/plugins/credentials.hpi.pinned && \
    ln -s /usr/lib64/jenkins/durable-task.hpi /opt/openshift/plugins/durable-task.hpi && \
    ln -s /usr/lib64/jenkins/kubernetes.hpi /opt/openshift/plugins/kubernetes.hpi && \
    /usr/local/bin/fix-permissions /opt/openshift && \
    chown -R 1001:0 /opt/openshift && \
    /usr/local/bin/fix-permissions /var/lib/jenkins

VOLUME ["/var/lib/jenkins"]

USER 1001
CMD ["/usr/libexec/s2i/run"]

LABEL "distribution-scope"="public" "Build_Host"="rcm-img-docker02.build.eng.bos.redhat.com" "vcs-type"="git" "build-date"="2016-06-10T10:27:58.834699Z" "vcs-ref"="0e4dddb4a63710b32cf3d37fa95f4f907f41d4bd" "com.redhat.build-host"="rcm-img-docker02.build.eng.bos.redhat.com" "architecture"="x86_64"

