apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: null
  generation: 1
  name: jenkins2
spec:
  tags:
  - annotations: null
    generation: 1
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
